In [15]:
import numpy as np
X = np.arange(12).reshape(4,3)
w = np.array([1,2,3])
y = np.array([7,7,7,7])

print(X.shape[1])
yy=np.dot(X,w)
print(f"shape of X {X.shape},shape of w {w.shape},shape of yy {yy.shape}")
print(X.T)
print(yy-y)

grad = (2/X.shape[0])*np.dot(X.T, (np.dot(X ,w) - y))
print(grad)
print(grad.shape)

3
shape of X (4, 3),shape of w (3,),shape of yy (4,)
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[ 1 19 37 55]
[387. 443. 499.]
(3,)
