In [5]:

import numpy as np

z = np.arange(10).reshape(2,5)
print(z)
print(z.shape)


[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [6]:
print(z.shape[0])

2


In [7]:
print(z+1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
print(np.argmax(z))

9


TypeError: 'numpy.ndarray' object is not callable